const menu = [
    {
      id: 1,
      title: 'Accurate',
      category: 'django',
      img: '/img/heart.png',
      desc: `A medicine dose tracker with a cronjob service in order to alert users with dose time `,
    },
    {
      id: 2,
      title: 'Medical Appoitment system ',
      category: 'django',
      img: './images/item-2.jpeg',
      desc: `Midical appoitment system where the customer can add or cancel their appoitment `,
    },
    {
      id: 3,
      title: 'Sleep tracker ',
      category: 'ASP.NET',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `A sleep tracker with charts monitoring for averrage sleeping`,
    },
    {
      id: 4,
      title: 'cozy shop',
      category: 'MERN',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `A pizza delivery shop with stripe extension`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'MERN',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'Angular',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'Angular',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'Flutter',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'Flutter',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  